In [1]:
import pandas as pd

In [9]:
movies = pd.read_csv("data/movies.csv", encoding = 'cp949')

In [10]:
movies.head(10)

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
0,Zack and Miri Make a Porno,Romance,The Weinstein Company,70,1.747542,64,$41.94,2008
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68,$19.62,2010
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43,$26.66,2010
3,When in Rome,Comedy,Disney,44,0.000000,15,$43.04,2010
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28,$219.37,2008
5,Water For Elephants,Drama,20th Century Fox,72,3.081421,60,$117.09,2011
6,WALL-E,Animation,Disney,89,2.896019,96,$521.28,2008
7,Waitress,Romance,Independent,67,11.089742,89,$22.18,2007
8,Waiting For Forever,Romance,Independent,53,0.005000,6,$0.03,2011
9,Valentine's Day,Comedy,Warner Bros.,54,4.184038,17,$217.57,2010

In [29]:
best_m = movies['Audience score %'] > 85

In [17]:
import numpy as np

In [18]:
movies['best3_movie'] = ""

In [19]:
movies

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year,best3_movie
0,Zack and Miri Make a Porno,Romance,The Weinstein Company,70,1.747542,64,$41.94,2008,
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68,$19.62,2010,
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43,$26.66,2010,
3,When in Rome,Comedy,Disney,44,0.000000,15,$43.04,2010,
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28,$219.37,2008,
...,...,...,...,...,...,...,...,...,...
72,Across the Universe,romance,Independent,84,0.652603,54,$29.37,2007,
73,A Serious Man,Drama,Universal,64,4.382857,89,$30.68,2009,
74,A Dangerous Method,Drama,Independent,89,0.448645,79,$8.97,2011,
75,27 Dresses,Comedy,Fox,71,5.343622,40,$160.31,2008,
76,(500) Days of Summer,comedy,Fox,81,8.096000,87,$60.72,2009,

In [30]:
best_m

0     False
1     False
2     False
3     False
4     False
      ...
72    False
73    False
74     True
75    False
76    False
Name: Audience score %, Length: 77, dtype: bool

In [22]:
np.where(best_m,'best movie',' ')

array([['best movie', 'best movie', 'best movie', 'best movie',
        'best movie', 'best movie', 'best movie', 'best movie', ' '],
       ['best movie', 'best movie', 'best movie', 'best movie',
        'best movie', 'best movie', 'best movie', 'best movie', ' '],
       ['best movie', 'best movie', 'best movie', 'best movie',
        'best movie', 'best movie', 'best movie', 'best movie', ' ']],
      dtype='<U10')

In [31]:
movies['best3_movie']  = pd.Categorical(np.where(best_m, 'best movie', ' '))

In [32]:
movies.head(20)

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year,best3_movie
0,Zack and Miri Make a Porno,Romance,The Weinstein Company,70,1.747542,64,$41.94,2008,
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68,$19.62,2010,
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43,$26.66,2010,
3,When in Rome,Comedy,Disney,44,0.000000,15,$43.04,2010,
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28,$219.37,2008,
5,Water For Elephants,Drama,20th Century Fox,72,3.081421,60,$117.09,2011,
6,WALL-E,Animation,Disney,89,2.896019,96,$521.28,2008,best movie
7,Waitress,Romance,Independent,67,11.089742,89,$22.18,2007,
8,Waiting For Forever,Romance,Independent,53,0.005000,6,$0.03,2011,
9,Valentine's Day,Comedy,Warner Bros.,54,4.184038,17,$217.57,2010,
10,Tyler Perry's Why Did I get Married,Romance,Independent,47,3.724192,46,$55.86,2007,
11,Twilight: Breaking Dawn,Romance,Independent,68,6.383364,26,$702.17,2011,
12,Twilight,Romance,Summit,82,10.180027,49,$376.66,2008,
13,The Ugly Truth,Comedy,Independent,68,5.402632,14,$205.30,2009,
14,The Twilight Saga: New Moon,Drama,Summit,78,14.196400,27,$709.82,2009,
15,The Time Traveler's Wife,Drama,Paramount,65,2.598205,38,$101.33,2009,
16,The Proposal,Comedy,Disney,74,7.867500,43,$314.70,2009,
17,The Invention of Lying,Comedy,Warner Bros.,47,1.751351,56,$32.40,2009,
18,The Heartbreak Kid,Comedy,Paramount,41,2.129444,30,$127.77,2007,
19,The Duchess,Drama,Paramount,68,3.207850,60,$43.31,2008,