In [1]:
import pandas as pd

In [35]:
movie = pd.read_csv('data/movies.csv',encoding='cp949')

In [37]:
movie.head()

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
0,Zack and Miri Make a Porno,Romance,The Weinstein Company,70,1.747542,64,$41.94,2008
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68,$19.62,2010
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43,$26.66,2010
3,When in Rome,Comedy,Disney,44,0.000000,15,$43.04,2010
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28,$219.37,2008

In [49]:
movie.loc[(movie['Genre'] == 'Comedy') & (movie['Audience score %'] < 70),: ]

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68,$19.62,2010
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43,$26.66,2010
3,When in Rome,Comedy,Disney,44,0.000000,15,$43.04,2010
9,Valentine's Day,Comedy,Warner Bros.,54,4.184038,17,$217.57,2010
13,The Ugly Truth,Comedy,Independent,68,5.402632,14,$205.30,2009
17,The Invention of Lying,Comedy,Warner Bros.,47,1.751351,56,$32.40,2009
18,The Heartbreak Kid,Comedy,Paramount,41,2.129444,30,$127.77,2007
21,The Back-up Plan,Comedy,CBS,47,2.202571,20,$77.09,2010
24,She's Out of My League,Comedy,Paramount,60,2.440500,57,$48.81,2010
25,Sex and the City Two,Comedy,Warner Bros.,49,2.883500,15,$288.35,2010
26,Sex and the City 2,Comedy,Warner Bros.,49,2.883500,15,$288.35,2010
32,Over Her Dead Body,Comedy,New Line,47,2.071000,15,$20.71,2008
33,Our Family Wedding,Comedy,Independent,49,0.000000,14,$21.37,2010
36,No Reservations,Comedy,Warner Bros.,64,3.307180,39,$92.60,2007
37,Nick and Norah's Infinite Playlist,Comedy,Sony,67,3.352729,73,$33.53,2008
49,Love & Other Drugs,Comedy,Fox,55,1.817667,48,$54.53,2010
50,Life as We Know It,Comedy,Independent,62,2.530526,28,$96.16,2010
51,License to Wed,Comedy,Warner Bros.,55,1.980206,8,$69.31,2007
52,Letters to Juliet,Comedy,Summit,62,2.639333,40,$79.18,2010
53,Leap Year,Comedy,Universal,49,1.715263,21,$32.59,2010
56,Just Wright,Comedy,Fox,58,1.797417,45,$21.57,2010
58,It's Complicated,Comedy,Universal,63,2.642353,56,$224.60,2009
59,I Love You Phillip Morris,Comedy,Independent,57,1.340000,71,$20.10,2010
61,He's Just Not That Into You,Comedy,Warner Bros.,60,7.153600,42,$178.84,2009
62,Good Luck Chuck,Comedy,Lionsgate,61,2.367685,3,$59.19,2007
63,Going the Distance,Comedy,Warner Bros.,56,1.314062,53,$42.05,2010
66,Ghosts of Girlfriends Past,Comedy,Warner Bros.,47,2.044400,27,$102.22,2009
67,Four Christmases,Comedy,Warner Bros.,52,2.022925,26,$161.83,2008

In [105]:
movie_best = movie['Audience score %'].between(85,100)
#movie_best = movie[(movie['Genre'] == 'Comedy') & (movie['Audience score %'].between(70,100))]

In [106]:
movie_best

0     False
1     False
2     False
3     False
4     False
      ...
72    False
73    False
74     True
75    False
76    False
Name: Audience score %, Length: 77, dtype: bool

In [107]:
import numpy as np

In [108]:
movie['best3_movie'] = ""

In [109]:
movie

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year,best3_movie,best_Comedy_movie
0,Zack and Miri Make a Porno,Romance,The Weinstein Company,70,1.747542,64,$41.94,2008,,
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68,$19.62,2010,,
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43,$26.66,2010,,
3,When in Rome,Comedy,Disney,44,0.000000,15,$43.04,2010,,
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28,$219.37,2008,,
...,...,...,...,...,...,...,...,...,...,...
72,Across the Universe,romance,Independent,84,0.652603,54,$29.37,2007,,
73,A Serious Man,Drama,Universal,64,4.382857,89,$30.68,2009,,
74,A Dangerous Method,Drama,Independent,89,0.448645,79,$8.97,2011,,
75,27 Dresses,Comedy,Fox,71,5.343622,40,$160.31,2008,,
76,(500) Days of Summer,comedy,Fox,81,8.096000,87,$60.72,2009,,

In [110]:
np.where(movie_best,'*best3_movie*',' ')

array([' ', ' ', ' ', ' ', ' ', ' ', '*best3_movie*', ' ', ' ', ' ', ' ',
       ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
       '*best3_movie*', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
       ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
       ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
       ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
       ' ', ' ', '*best3_movie*', ' ', ' '], dtype='<U13')

In [111]:
movie['best3_movie'] = pd.Categorical(np.where(movie_best,'*best3_movie*',' '))

In [112]:
movie.head(20)

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year,best3_movie,best_Comedy_movie
0,Zack and Miri Make a Porno,Romance,The Weinstein Company,70,1.747542,64,$41.94,2008,,
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68,$19.62,2010,,
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43,$26.66,2010,,
3,When in Rome,Comedy,Disney,44,0.000000,15,$43.04,2010,,
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28,$219.37,2008,,
5,Water For Elephants,Drama,20th Century Fox,72,3.081421,60,$117.09,2011,,
6,WALL-E,Animation,Disney,89,2.896019,96,$521.28,2008,*best3_movie*,
7,Waitress,Romance,Independent,67,11.089742,89,$22.18,2007,,
8,Waiting For Forever,Romance,Independent,53,0.005000,6,$0.03,2011,,
9,Valentine's Day,Comedy,Warner Bros.,54,4.184038,17,$217.57,2010,,
10,Tyler Perry's Why Did I get Married,Romance,Independent,47,3.724192,46,$55.86,2007,,
11,Twilight: Breaking Dawn,Romance,Independent,68,6.383364,26,$702.17,2011,,
12,Twilight,Romance,Summit,82,10.180027,49,$376.66,2008,,
13,The Ugly Truth,Comedy,Independent,68,5.402632,14,$205.30,2009,,
14,The Twilight Saga: New Moon,Drama,Summit,78,14.196400,27,$709.82,2009,,
15,The Time Traveler's Wife,Drama,Paramount,65,2.598205,38,$101.33,2009,,
16,The Proposal,Comedy,Disney,74,7.867500,43,$314.70,2009,,
17,The Invention of Lying,Comedy,Warner Bros.,47,1.751351,56,$32.40,2009,,
18,The Heartbreak Kid,Comedy,Paramount,41,2.129444,30,$127.77,2007,,
19,The Duchess,Drama,Paramount,68,3.207850,60,$43.31,2008,,